import type { RevenueProviderCapabilities } from "./verifiedRevenueMetrics.js";

const catalog: RevenueProviderCapabilities[] = [
  {
    slug: "stripe",
    displayName: "Stripe",
    revenueClass: "subscription",
    authType: "api_key",
    supports_mrr: true,
    supports_arr: true,
    supports_transactions: true,
    supports_customers: true,
    apiKeyPlaceholder: "sk_live_… or sk_test_…",
    apiKeyHint: "Secret key from Stripe Dashboard → Developers → API keys.",
    connectDescription:
      "We aggregate recent balance transactions into verified monthly revenue.",
    partialHint:
      "Connect the same key where charges appear (test mode is fine for sandbox).",
  },
  {
    slug: "paddle",
    displayName: "Paddle",
    revenueClass: "subscription",
    authType: "api_key",
    supports_mrr: true,
    supports_arr: true,
    supports_transactions: true,
    supports_customers: false,
    apiKeyPlaceholder: "Paddle Billing API key",
    connectDescription: "Uses Paddle transaction totals for verified revenue.",
  },
  {
    slug: "revenuecat",
    displayName: "RevenueCat",
    revenueClass: "subscription",
    authType: "api_key",
    supports_mrr: true,
    supports_arr: true,
    supports_transactions: false,
    supports_customers: true,
    requiresExternalAccount: true,
    externalAccountLabel: "Project ID",
    apiKeyPlaceholder: "RevenueCat secret API key",
    connectDescription: "Subscription metrics from your RevenueCat project.",
  },
  {
    slug: "chargebee",
    displayName: "Chargebee",
    revenueClass: "subscription",
    authType: "api_key",
    supports_mrr: true,
    supports_arr: true,
    supports_transactions: true,
    supports_customers: true,
    requiresExternalAccount: true,
    externalAccountLabel: "Site name (subdomain)",
    apiKeyPlaceholder: "Chargebee API key",
  },
  {
    slug: "recurly",
    displayName: "Recurly",
    revenueClass: "subscription",
    authType: "api_key",
    supports_mrr: true,
    supports_arr: true,
    supports_transactions: true,
    supports_customers: true,
    requiresExternalAccount: true,
    externalAccountLabel: "Subdomain",
    apiKeyPlaceholder: "Recurly private API key",
  },
  {
    slug: "lemonsqueezy",
    displayName: "Lemon Squeezy",
    revenueClass: "subscription",
    authType: "api_key",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
    apiKeyPlaceholder: "Lemon Squeezy API key",
    connectDescription: "Verified revenue from recent store orders.",
  },
  {
    slug: "razorpay",
    displayName: "Razorpay",
    revenueClass: "transaction",
    authType: "api_key",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
    apiKeyPlaceholder: "key_id:key_secret",
    apiKeyHint: "Paste as key_id:key_secret from Razorpay Dashboard.",
    connectDescription: "Sums captured payments in the verification window.",
  },
  {
    slug: "paypal",
    displayName: "PayPal",
    revenueClass: "transaction",
    authType: "oauth2",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
    connectDescription:
      "OAuth to PayPal — transaction totals in the sync window.",
  },
  {
    slug: "square",
    displayName: "Square",
    revenueClass: "transaction",
    authType: "oauth2",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
  },
  {
    slug: "payu",
    displayName: "PayU",
    revenueClass: "transaction",
    authType: "api_key",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
    apiKeyPlaceholder: "PayU merchant key",
  },
  {
    slug: "shopify",
    displayName: "Shopify",
    revenueClass: "commerce",
    authType: "oauth2",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: true,
    requiresExternalAccount: true,
    externalAccountLabel: "Shop domain (myshop.myshopify.com)",
    connectDescription: "Order totals from your Shopify store.",
  },
  {
    slug: "woocommerce",
    displayName: "WooCommerce",
    revenueClass: "commerce",
    authType: "api_key",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
    requiresExternalAccount: true,
    externalAccountLabel: "Store URL (https://…)",
    apiKeyPlaceholder: "Consumer key:consumer secret",
  },
  {
    slug: "bigcommerce",
    displayName: "BigCommerce",
    revenueClass: "commerce",
    authType: "api_key",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
    requiresExternalAccount: true,
    externalAccountLabel: "Store hash",
    apiKeyPlaceholder: "BigCommerce API token",
  },
  {
    slug: "quickbooks",
    displayName: "QuickBooks",
    revenueClass: "accounting",
    authType: "oauth2",
    supports_mrr: false,
    supports_arr: true,
    supports_transactions: false,
    supports_customers: false,
    requiresExternalAccount: true,
    externalAccountLabel: "Company ID (realmId)",
    connectDescription:
      "Accounting revenue — P&L based verified amount (not MRR).",
  },
  {
    slug: "xero",
    displayName: "Xero",
    revenueClass: "accounting",
    authType: "oauth2",
    supports_mrr: false,
    supports_arr: true,
    supports_transactions: false,
    supports_customers: false,
    requiresExternalAccount: true,
    externalAccountLabel: "Tenant ID",
  },
  {
    slug: "zoho_books",
    displayName: "Zoho Books",
    revenueClass: "accounting",
    authType: "oauth2",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: false,
    supports_customers: false,
    requiresExternalAccount: true,
    externalAccountLabel: "Organization ID",
  },
  {
    slug: "plaid",
    displayName: "Plaid",
    revenueClass: "banking",
    authType: "link",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
    connectDescription: "Bank inflows in the verification window.",
  },
  {
    slug: "tink",
    displayName: "Tink",
    revenueClass: "banking",
    authType: "oauth2",
    supports_mrr: false,
    supports_arr: false,
    supports_transactions: true,
    supports_customers: false,
  },
];

const bySlug = new Map(catalog.map((c) => [c.slug, c]));

export function getRevenueProviderCapabilities(
  slug: string,
): RevenueProviderCapabilities | undefined {
  return bySlug.get(slug);
}

export function listRevenueProviderCapabilities(): RevenueProviderCapabilities[] {
  return catalog;
}

export function revenueProvidersForAuthType(
  authType: RevenueProviderCapabilities["authType"],
): RevenueProviderCapabilities[] {
  return catalog.filter((c) => c.authType === authType);
}
