-- Generated by artifacts/ownerr-web-app/scripts/generate-marketplace-seed-sql.mjs

begin;

delete from public.startup_metrics where startup_id in (select id from public.startups where slug like 'seed-%' or slug in (select slug from public.startups));

delete from public.startup_media where startup_id in (select id from public.startups);

delete from public.seller_listings where startup_id in (select id from public.startups);

delete from public.startups;

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'stan',
    'vitddnv',
    'Stan',
    null,
    'Stan enables people to make a living and work for themselves.',
    'Content Creation',
    'live',
    null,
    'USD',
    42835848,
    null,
    12.5,
    45000,
    2020,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":1093572},{"month":"Feb","value":1285641},{"month":"Mar","value":1449078},{"month":"Apr","value":1560470},{"month":"May","value":1663622},{"month":"Jun","value":1734448},{"month":"Jul","value":1712581},{"month":"Aug","value":1967366},{"month":"Sep","value":2314890},{"month":"Oct","value":2526867},{"month":"Nov","value":2523513},{"month":"Dec","value":3569654}],"logo_color":"#E6EAFF","business_score":100,"lend_score":100,"acquisition_power":83,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":112500,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":12.5,"customers":45000,"peak_mrr":3748137,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'sorio-ai',
    'alicew',
    'Sorio AI',
    null,
    'AI-powered writing assistant for B2B marketers.',
    'Artificial Intelligence',
    'live',
    250000,
    'USD',
    150000,
    95000,
    8.2,
    340,
    2023,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":4454},{"month":"Feb","value":4865},{"month":"Mar","value":5434},{"month":"Apr","value":5599},{"month":"May","value":6700},{"month":"Jun","value":6712},{"month":"Jul","value":7061},{"month":"Aug","value":6727},{"month":"Sep","value":7274},{"month":"Oct","value":7209},{"month":"Nov","value":8584},{"month":"Dec","value":12500}],"logo_color":"#E6FFE8","business_score":83,"lend_score":99,"acquisition_power":84,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":850,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":8.2,"customers":340,"peak_mrr":13125,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'cursorclip',
    'robbyf',
    'CursorClip',
    null,
    'Capture cursor recordings beautifully.',
    'Content Creation',
    'live',
    29000,
    'USD',
    15600,
    9000,
    5.1,
    120,
    2024,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":380},{"month":"Feb","value":365},{"month":"Mar","value":359},{"month":"Apr","value":392},{"month":"May","value":407},{"month":"Jun","value":412},{"month":"Jul","value":451},{"month":"Aug","value":449},{"month":"Sep","value":535},{"month":"Oct","value":613},{"month":"Nov","value":731},{"month":"Dec","value":1300}],"logo_color":"#FFE6F1","business_score":77,"lend_score":86,"acquisition_power":79,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":300,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":5.1,"customers":120,"peak_mrr":1508,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'iqmax',
    'marcdev',
    'IQMax',
    null,
    'Daily IQ workout app.',
    'Education',
    'live',
    4000,
    'USD',
    7440,
    2500,
    -3.2,
    80,
    2024,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":193},{"month":"Feb","value":224},{"month":"Mar","value":217},{"month":"Apr","value":217},{"month":"May","value":256},{"month":"Jun","value":295},{"month":"Jul","value":289},{"month":"Aug","value":286},{"month":"Sep","value":298},{"month":"Oct","value":288},{"month":"Nov","value":304},{"month":"Dec","value":620}],"logo_color":"#E6F5FF","business_score":63,"lend_score":68,"acquisition_power":73,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":200,"traffic_trend":"flat","listing_views":0,"listing_favorites":0,"mom_growth":-3.2,"customers":80,"peak_mrr":645,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'holypoly',
    'cryptodan',
    'Holypoly',
    null,
    'Liquid staking on every chain.',
    'Crypto & Web3',
    'live',
    80000,
    'USD',
    132000,
    60000,
    1.4,
    800,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":3375},{"month":"Feb","value":3370},{"month":"Mar","value":3571},{"month":"Apr","value":4166},{"month":"May","value":4337},{"month":"Jun","value":4879},{"month":"Jul","value":4958},{"month":"Aug","value":5441},{"month":"Sep","value":5276},{"month":"Oct","value":5043},{"month":"Nov","value":5415},{"month":"Dec","value":11000}],"logo_color":"#F0E6FF","business_score":80,"lend_score":92,"acquisition_power":84,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":2000,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":1.4,"customers":800,"peak_mrr":13530,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'polysight-app',
    'yoava',
    'polysight.app',
    null,
    'Your all in one tool for making money online.',
    'SaaS',
    'live',
    1000000,
    'USD',
    192000,
    110000,
    6,
    540,
    2021,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":5004},{"month":"Feb","value":4978},{"month":"Mar","value":5493},{"month":"Apr","value":6361},{"month":"May","value":6523},{"month":"Jun","value":6907},{"month":"Jul","value":8069},{"month":"Aug","value":8456},{"month":"Sep","value":8533},{"month":"Oct","value":8425},{"month":"Nov","value":8810},{"month":"Dec","value":16000}],"logo_color":"#E6EAFF","business_score":90,"lend_score":99,"acquisition_power":82,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":1350,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":6,"customers":540,"peak_mrr":19520,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'sacred-bible',
    'ianmarco',
    'Sacred: Bible & Daily Devotion',
    null,
    'Daily devotionals and Bible reading.',
    'Mobile Apps',
    'live',
    11000,
    'USD',
    11916,
    4000,
    9.2,
    220,
    2024,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":353},{"month":"Feb","value":341},{"month":"Mar","value":379},{"month":"Apr","value":392},{"month":"May","value":396},{"month":"Jun","value":430},{"month":"Jul","value":430},{"month":"Aug","value":475},{"month":"Sep","value":496},{"month":"Oct","value":493},{"month":"Nov","value":484},{"month":"Dec","value":993}],"logo_color":"#FFEEE6","business_score":70,"lend_score":78,"acquisition_power":80,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":550,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":9.2,"customers":220,"peak_mrr":1271,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'dunkmax',
    'janed',
    'DunkMax',
    null,
    'Vertical jump training program app.',
    'Mobile Apps',
    'live',
    155000,
    'USD',
    84000,
    32000,
    4,
    410,
    2023,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":2202},{"month":"Feb","value":2547},{"month":"Mar","value":2648},{"month":"Apr","value":3026},{"month":"May","value":3456},{"month":"Jun","value":3762},{"month":"Jul","value":4164},{"month":"Aug","value":4835},{"month":"Sep","value":5043},{"month":"Oct","value":5314},{"month":"Nov","value":6090},{"month":"Dec","value":7000}],"logo_color":"#FFF8E6","business_score":81,"lend_score":89,"acquisition_power":87,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":1025,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":4,"customers":410,"peak_mrr":7630,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'oli-ai',
    'alicew',
    'Oli Ai',
    null,
    'AI olive oil sommelier.',
    'Artificial Intelligence',
    'live',
    50000,
    'USD',
    13200,
    4500,
    14,
    60,
    2024,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":322},{"month":"Feb","value":380},{"month":"Mar","value":400},{"month":"Apr","value":453},{"month":"May","value":482},{"month":"Jun","value":510},{"month":"Jul","value":604},{"month":"Aug","value":662},{"month":"Sep","value":682},{"month":"Oct","value":704},{"month":"Nov","value":737},{"month":"Dec","value":1100}],"logo_color":"#E6FFE8","business_score":80,"lend_score":79,"acquisition_power":74,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":200,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":14,"customers":60,"peak_mrr":1265,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'b2c-b2b-proxy',
    'sowak',
    'B2C & B2B Proxy Company',
    null,
    'Residential proxy network.',
    'Developer Tools',
    'live',
    249000,
    'USD',
    204000,
    130000,
    2.4,
    380,
    2021,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":4975},{"month":"Feb","value":5940},{"month":"Mar","value":6768},{"month":"Apr","value":8099},{"month":"May","value":8175},{"month":"Jun","value":8117},{"month":"Jul","value":8470},{"month":"Aug","value":10117},{"month":"Sep","value":9797},{"month":"Oct","value":11720},{"month":"Nov","value":12845},{"month":"Dec","value":17000}],"logo_color":"#FFE6F1","business_score":84,"lend_score":97,"acquisition_power":86,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":950,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":2.4,"customers":380,"peak_mrr":18190,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'conduzy',
    'janed',
    'Conduzy',
    null,
    'Drivers ed app for new drivers.',
    'Mobile Apps',
    'live',
    250000,
    'USD',
    168000,
    90000,
    7.2,
    1100,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":4531},{"month":"Feb","value":4777},{"month":"Mar","value":4619},{"month":"Apr","value":4993},{"month":"May","value":4763},{"month":"Jun","value":5388},{"month":"Jul","value":5973},{"month":"Aug","value":6199},{"month":"Sep","value":6921},{"month":"Oct","value":8172},{"month":"Nov","value":8300},{"month":"Dec","value":14000}],"logo_color":"#E6EAFF","business_score":90,"lend_score":97,"acquisition_power":91,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":2750,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":7.2,"customers":1100,"peak_mrr":15400,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'trimrx',
    'heygrant',
    'TrimRx',
    null,
    'Online telehealth GLP-1 weight loss programs.',
    'Health',
    'live',
    null,
    'USD',
    3726324,
    null,
    13,
    12000,
    2023,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":97616},{"month":"Feb","value":95924},{"month":"Mar","value":108210},{"month":"Apr","value":108189},{"month":"May","value":123460},{"month":"Jun","value":125997},{"month":"Jul","value":121551},{"month":"Aug","value":139128},{"month":"Sep","value":152870},{"month":"Oct","value":176255},{"month":"Nov","value":180932},{"month":"Dec","value":310527}],"logo_color":"#E6FFE8","business_score":100,"lend_score":98,"acquisition_power":78,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":30000,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":13,"customers":12000,"peak_mrr":332264,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'rezi',
    'jacobj',
    'Rezi',
    null,
    'AI resume builder used by 1M+ users yearly.',
    'SaaS',
    'live',
    4500000,
    'USD',
    3424092,
    1800000,
    2,
    1000000,
    2019,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":102329},{"month":"Feb","value":119564},{"month":"Mar","value":136941},{"month":"Apr","value":156902},{"month":"May","value":170881},{"month":"Jun","value":173781},{"month":"Jul","value":197700},{"month":"Aug","value":200377},{"month":"Sep","value":204268},{"month":"Oct","value":231070},{"month":"Nov","value":259928},{"month":"Dec","value":285341}],"logo_color":"#FFE6F1","business_score":100,"lend_score":100,"acquisition_power":97,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":2500000,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":2,"customers":1000000,"peak_mrr":311022,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'kibu',
    'danielc',
    'Kibu',
    null,
    'EHR for I/DD provider organizations.',
    'SaaS',
    'live',
    null,
    'USD',
    2811828,
    null,
    0,
    320,
    2018,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":77298},{"month":"Feb","value":91561},{"month":"Mar","value":97252},{"month":"Apr","value":104385},{"month":"May","value":100859},{"month":"Jun","value":103919},{"month":"Jul","value":121804},{"month":"Aug","value":137504},{"month":"Sep","value":138449},{"month":"Oct","value":163816},{"month":"Nov","value":188593},{"month":"Dec","value":234319}],"logo_color":"#E6F5FF","business_score":98,"lend_score":100,"acquisition_power":71,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":800,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":0,"customers":320,"peak_mrr":262437,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    '1capture',
    'robbyf',
    '1Capture',
    null,
    'Double your trial-to-paid conversion.',
    'Marketing',
    'live',
    2400000,
    'USD',
    2594952,
    1200000,
    0,
    740,
    2020,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":64903},{"month":"Feb","value":69270},{"month":"Mar","value":81128},{"month":"Apr","value":77116},{"month":"May","value":90875},{"month":"Jun","value":96398},{"month":"Jul","value":97883},{"month":"Aug","value":111194},{"month":"Sep","value":124806},{"month":"Oct","value":133167},{"month":"Nov","value":128924},{"month":"Dec","value":216246}],"logo_color":"#FFEEE6","business_score":94,"lend_score":100,"acquisition_power":94,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":1850,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":0,"customers":740,"peak_mrr":261658,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'cometly',
    'heygrant',
    'Cometly',
    null,
    'Marketing attribution & analytics for SaaS.',
    'Marketing',
    'live',
    null,
    'USD',
    2545944,
    null,
    4,
    900,
    2021,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":72324},{"month":"Feb","value":84233},{"month":"Mar","value":97099},{"month":"Apr","value":94989},{"month":"May","value":97043},{"month":"Jun","value":94075},{"month":"Jul","value":94896},{"month":"Aug","value":94831},{"month":"Sep","value":109787},{"month":"Oct","value":123783},{"month":"Nov","value":128857},{"month":"Dec","value":212162}],"logo_color":"#F0E6FF","business_score":100,"lend_score":99,"acquisition_power":74,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":2250,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":4,"customers":900,"peak_mrr":277932,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'supliful',
    'sarahj',
    'Brand On Demand, Inc.',
    null,
    'CPG brand launch platform for creators.',
    'SaaS',
    'live',
    null,
    'USD',
    2380800,
    null,
    8.5,
    5400,
    2020,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":70486},{"month":"Feb","value":74938},{"month":"Mar","value":81251},{"month":"Apr","value":88332},{"month":"May","value":94076},{"month":"Jun","value":91092},{"month":"Jul","value":88697},{"month":"Aug","value":97901},{"month":"Sep","value":104095},{"month":"Oct","value":124728},{"month":"Nov","value":130002},{"month":"Dec","value":198400}],"logo_color":"#E6FFE8","business_score":100,"lend_score":100,"acquisition_power":72,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":13500,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":8.5,"customers":5400,"peak_mrr":236096,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'dm-champ',
    'sowak',
    'DM Champ',
    null,
    'AI sales agent that closes 24/7.',
    'Artificial Intelligence',
    'live',
    null,
    'USD',
    2305860,
    null,
    22,
    410,
    2023,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":66148},{"month":"Feb","value":75062},{"month":"Mar","value":86905},{"month":"Apr","value":93382},{"month":"May","value":108942},{"month":"Jun","value":119687},{"month":"Jul","value":121087},{"month":"Aug","value":142047},{"month":"Sep","value":149974},{"month":"Oct","value":148113},{"month":"Nov","value":162147},{"month":"Dec","value":192155}],"logo_color":"#FFF8E6","business_score":100,"lend_score":99,"acquisition_power":82,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":1025,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":22,"customers":410,"peak_mrr":199841,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'stealth-venture',
    'nomistair',
    'Stealth Venture',
    null,
    'Currently unannounced.',
    'SaaS',
    'live',
    null,
    'USD',
    2204196,
    null,
    4,
    420,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":54552},{"month":"Feb","value":57147},{"month":"Mar","value":63330},{"month":"Apr","value":63002},{"month":"May","value":61329},{"month":"Jun","value":60673},{"month":"Jul","value":59038},{"month":"Aug","value":69152},{"month":"Sep","value":80782},{"month":"Oct","value":83435},{"month":"Nov","value":81128},{"month":"Dec","value":183683}],"logo_color":"#E6EAFF","business_score":93,"lend_score":95,"acquisition_power":70,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":1050,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":4,"customers":420,"peak_mrr":214909,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'hidden-business',
    'sowak',
    'Hidden Business',
    null,
    'Stealth project.',
    'SaaS',
    'live',
    null,
    'USD',
    1884156,
    null,
    0,
    280,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":52707},{"month":"Feb","value":51174},{"month":"Mar","value":58721},{"month":"Apr","value":63675},{"month":"May","value":65372},{"month":"Jun","value":71756},{"month":"Jul","value":79475},{"month":"Aug","value":77502},{"month":"Sep","value":89604},{"month":"Oct","value":102644},{"month":"Nov","value":97658},{"month":"Dec","value":157013}],"logo_color":"#FFE6F1","business_score":96,"lend_score":100,"acquisition_power":75,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":700,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":0,"customers":280,"peak_mrr":182135,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'dealsourcr',
    'ashleyr',
    'Dealsourcr Ltd',
    null,
    'Software for deal sourcing teams.',
    'SaaS',
    'live',
    null,
    'USD',
    1827696,
    null,
    25,
    340,
    2021,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":48402},{"month":"Feb","value":52212},{"month":"Mar","value":52557},{"month":"Apr","value":61807},{"month":"May","value":68305},{"month":"Jun","value":74012},{"month":"Jul","value":82400},{"month":"Aug","value":80717},{"month":"Sep","value":84756},{"month":"Oct","value":97360},{"month":"Nov","value":93675},{"month":"Dec","value":152308}],"logo_color":"#E6F5FF","business_score":100,"lend_score":99,"acquisition_power":73,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":850,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":25,"customers":340,"peak_mrr":170585,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'dataexpert',
    'zachw',
    'DataExpert / TechCreator',
    null,
    'DataExpert.io is a data engineering education platform.',
    'Education',
    'live',
    null,
    'USD',
    753480,
    null,
    3,
    1800,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":21541},{"month":"Feb","value":23516},{"month":"Mar","value":28156},{"month":"Apr","value":32999},{"month":"May","value":36625},{"month":"Jun","value":40228},{"month":"Jul","value":40967},{"month":"Aug","value":46904},{"month":"Sep","value":55957},{"month":"Oct","value":62100},{"month":"Nov","value":73479},{"month":"Dec","value":62790}],"logo_color":"#FFEEE6","business_score":95,"lend_score":100,"acquisition_power":69,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":4500,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":3,"customers":1800,"peak_mrr":70953,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'besbet',
    'kevinyu',
    'besbet',
    null,
    'Sportsbook analytics platform.',
    'SaaS',
    'live',
    null,
    'USD',
    636336,
    null,
    44,
    740,
    2023,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":15675},{"month":"Feb","value":16433},{"month":"Mar","value":17976},{"month":"Apr","value":18868},{"month":"May","value":22610},{"month":"Jun","value":22291},{"month":"Jul","value":26045},{"month":"Aug","value":29126},{"month":"Sep","value":33010},{"month":"Oct","value":34326},{"month":"Nov","value":35726},{"month":"Dec","value":53028}],"logo_color":"#E6EAFF","business_score":100,"lend_score":93,"acquisition_power":80,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":1850,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":44,"customers":740,"peak_mrr":59922,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-0',
    'vitddnv',
    'Lumen',
    null,
    'A small profitable indie product.',
    'SaaS',
    'live',
    null,
    'USD',
    299148,
    null,
    5.6,
    1150,
    2020,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":8682},{"month":"Feb","value":9263},{"month":"Mar","value":10003},{"month":"Apr","value":10520},{"month":"May","value":11232},{"month":"Jun","value":13445},{"month":"Jul","value":13795},{"month":"Aug","value":13238},{"month":"Sep","value":13069},{"month":"Oct","value":13026},{"month":"Nov","value":15533},{"month":"Dec","value":24929}],"logo_color":"#F0E6FF","business_score":91,"lend_score":89,"acquisition_power":67,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":11501,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":5.6,"customers":1150,"peak_mrr":29167,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-1',
    'alicew',
    'Pixly',
    null,
    'A small profitable indie product.',
    'Mobile Apps',
    'live',
    null,
    'USD',
    343680,
    null,
    3.3,
    1682,
    2021,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":9980},{"month":"Feb","value":11383},{"month":"Mar","value":11991},{"month":"Apr","value":12495},{"month":"May","value":12687},{"month":"Jun","value":12586},{"month":"Jul","value":12897},{"month":"Aug","value":13581},{"month":"Sep","value":14802},{"month":"Oct","value":15305},{"month":"Nov","value":16133},{"month":"Dec","value":28640}],"logo_color":"#E6FFE8","business_score":88,"lend_score":95,"acquisition_power":64,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":4064,"traffic_trend":"flat","listing_views":0,"listing_favorites":0,"mom_growth":3.3,"customers":1682,"peak_mrr":35800,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-2',
    'robbyf',
    'BrewMate',
    null,
    'A small profitable indie product.',
    'Developer Tools',
    'live',
    441968,
    'USD',
    172704,
    115136,
    0,
    676,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":4876},{"month":"Feb","value":5642},{"month":"Mar","value":5720},{"month":"Apr","value":6585},{"month":"May","value":6344},{"month":"Jun","value":6216},{"month":"Jul","value":7195},{"month":"Aug","value":7474},{"month":"Sep","value":8608},{"month":"Oct","value":8800},{"month":"Nov","value":10536},{"month":"Dec","value":14392}],"logo_color":"#E6EAFF","business_score":81,"lend_score":99,"acquisition_power":85,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":12312,"traffic_trend":"flat","listing_views":0,"listing_favorites":0,"mom_growth":0,"customers":676,"peak_mrr":15112,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-3',
    'sarahj',
    'Notewise',
    null,
    'A small profitable indie product.',
    'Marketing',
    'live',
    null,
    'USD',
    150108,
    null,
    4,
    666,
    2023,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":3658},{"month":"Feb","value":3680},{"month":"Mar","value":3581},{"month":"Apr","value":3583},{"month":"May","value":4088},{"month":"Jun","value":4732},{"month":"Jul","value":4981},{"month":"Aug","value":5252},{"month":"Sep","value":5382},{"month":"Oct","value":6077},{"month":"Nov","value":6295},{"month":"Dec","value":12509}],"logo_color":"#E6EAFF","business_score":89,"lend_score":87,"acquisition_power":65,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":10722,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":4,"customers":666,"peak_mrr":14135,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-4',
    'marcdev',
    'Forge',
    null,
    'A small profitable indie product.',
    'Artificial Intelligence',
    'live',
    154554,
    'USD',
    62364,
    41576,
    7.7,
    1906,
    2020,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":1486},{"month":"Feb","value":1525},{"month":"Mar","value":1492},{"month":"Apr","value":1462},{"month":"May","value":1405},{"month":"Jun","value":1656},{"month":"Jul","value":1855},{"month":"Aug","value":2011},{"month":"Sep","value":2379},{"month":"Oct","value":2764},{"month":"Nov","value":3291},{"month":"Dec","value":5197}],"logo_color":"#FFE6F1","business_score":83,"lend_score":99,"acquisition_power":77,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":15225,"traffic_trend":"flat","listing_views":0,"listing_favorites":0,"mom_growth":7.7,"customers":1906,"peak_mrr":6288,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-5',
    'janed',
    'Pulsar',
    null,
    'A small profitable indie product.',
    'SaaS',
    'live',
    null,
    'USD',
    120420,
    null,
    12.8,
    65,
    2021,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":3341},{"month":"Feb","value":3903},{"month":"Mar","value":3957},{"month":"Apr","value":4150},{"month":"May","value":4867},{"month":"Jun","value":4657},{"month":"Jul","value":4582},{"month":"Aug","value":4424},{"month":"Sep","value":4703},{"month":"Oct","value":4806},{"month":"Nov","value":5524},{"month":"Dec","value":10035}],"logo_color":"#E6FFE8","business_score":84,"lend_score":89,"acquisition_power":68,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":5893,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":12.8,"customers":65,"peak_mrr":12945,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-6',
    'cryptodan',
    'Nimbus',
    null,
    'A small profitable indie product.',
    'Mobile Apps',
    'live',
    null,
    'USD',
    265884,
    null,
    7.8,
    1728,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":6366},{"month":"Feb","value":6641},{"month":"Mar","value":6708},{"month":"Apr","value":6721},{"month":"May","value":7316},{"month":"Jun","value":7016},{"month":"Jul","value":8389},{"month":"Aug","value":8200},{"month":"Sep","value":8856},{"month":"Oct","value":10222},{"month":"Nov","value":11021},{"month":"Dec","value":22157}],"logo_color":"#FFE6F1","business_score":94,"lend_score":91,"acquisition_power":67,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":18345,"traffic_trend":"flat","listing_views":0,"listing_favorites":0,"mom_growth":7.8,"customers":1728,"peak_mrr":24151,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-7',
    'vitddnv',
    'Chime',
    null,
    'A small profitable indie product.',
    'Developer Tools',
    'live',
    null,
    'USD',
    439692,
    null,
    5.8,
    4303,
    2023,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":10793},{"month":"Feb","value":11923},{"month":"Mar","value":12989},{"month":"Apr","value":12484},{"month":"May","value":14961},{"month":"Jun","value":15575},{"month":"Jul","value":16523},{"month":"Aug","value":18487},{"month":"Sep","value":18978},{"month":"Oct","value":21141},{"month":"Nov","value":21533},{"month":"Dec","value":36641}],"logo_color":"#E6F5FF","business_score":92,"lend_score":98,"acquisition_power":66,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":12046,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":5.8,"customers":4303,"peak_mrr":42870,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-8',
    'alicew',
    'Echo',
    null,
    'A small profitable indie product.',
    'Marketing',
    'live',
    null,
    'USD',
    542244,
    null,
    9.3,
    367,
    2020,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":14404},{"month":"Feb","value":15076},{"month":"Mar","value":14541},{"month":"Apr","value":16979},{"month":"May","value":19428},{"month":"Jun","value":19297},{"month":"Jul","value":19579},{"month":"Aug","value":23011},{"month":"Sep","value":25629},{"month":"Oct","value":29110},{"month":"Nov","value":33459},{"month":"Dec","value":45187}],"logo_color":"#FFF8E6","business_score":90,"lend_score":96,"acquisition_power":73,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":4016,"traffic_trend":"flat","listing_views":0,"listing_favorites":0,"mom_growth":9.3,"customers":367,"peak_mrr":56484,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'mock-9',
    'robbyf',
    'Atlas',
    null,
    'A small profitable indie product.',
    'Artificial Intelligence',
    'live',
    null,
    'USD',
    834900,
    null,
    7.8,
    4891,
    2021,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":24467},{"month":"Feb","value":27555},{"month":"Mar","value":31384},{"month":"Apr","value":33707},{"month":"May","value":32600},{"month":"Jun","value":35517},{"month":"Jul","value":41773},{"month":"Aug","value":42361},{"month":"Sep","value":43037},{"month":"Oct","value":44589},{"month":"Nov","value":44269},{"month":"Dec","value":69575}],"logo_color":"#FFEEE6","business_score":99,"lend_score":94,"acquisition_power":71,"revenue_verified":true,"revenue_provider":"RevenueCat","domain_verified":true,"traffic_verified":false,"traffic_monthly_visitors":7150,"traffic_trend":"up","listing_views":0,"listing_favorites":0,"mom_growth":7.8,"customers":4891,"peak_mrr":73054,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'chatwith',
    'rafal',
    'Chatwith',
    null,
    'AI chatbots for agencies. Trained on website & files, fully white labeled, and with AI tool use.',
    'Customer Support',
    'live',
    147000,
    'USD',
    57600,
    null,
    6,
    150,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":1484},{"month":"Feb","value":1464},{"month":"Mar","value":1432},{"month":"Apr","value":1700},{"month":"May","value":1714},{"month":"Jun","value":1653},{"month":"Jul","value":1638},{"month":"Aug","value":1717},{"month":"Sep","value":1970},{"month":"Oct","value":1947},{"month":"Nov","value":2159},{"month":"Dec","value":4800}],"logo_color":"#1e3a5f","business_score":79,"lend_score":91,"acquisition_power":78,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":11253,"traffic_trend":"up","listing_views":3751,"listing_favorites":10,"mom_growth":6,"customers":150,"peak_mrr":5424,"asking_price_strike":null,"revenue_growth_30d_pct":6,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'sceneroll',
    'mrtars',
    'SceneRoll',
    null,
    'A better way to edit short-form faceless video. No editor timeline, no audio scrubber. Just upload audio, add your B-roll, and our app does the rest!',
    'Content Creation',
    'live',
    40000,
    'USD',
    51600,
    null,
    0,
    156,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":1406},{"month":"Feb","value":1597},{"month":"Mar","value":1717},{"month":"Apr","value":1791},{"month":"May","value":1868},{"month":"Jun","value":1961},{"month":"Jul","value":1880},{"month":"Aug","value":1907},{"month":"Sep","value":2065},{"month":"Oct","value":2459},{"month":"Nov","value":2933},{"month":"Dec","value":4300}],"logo_color":"#5c4033","business_score":74,"lend_score":85,"acquisition_power":86,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":11700,"traffic_trend":"up","listing_views":3900,"listing_favorites":7,"mom_growth":0,"customers":156,"peak_mrr":4902,"asking_price_strike":45000,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'post-bridge',
    'mrtars',
    'POST BRIDGE',
    null,
    'Post your content to multiple social media platforms at the same time, all-in one place.',
    'Social Media',
    'live',
    2500000,
    'USD',
    444000,
    null,
    17,
    880,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":12735},{"month":"Feb","value":12467},{"month":"Mar","value":13083},{"month":"Apr","value":12574},{"month":"May","value":13022},{"month":"Jun","value":15225},{"month":"Jul","value":15190},{"month":"Aug","value":16089},{"month":"Sep","value":17237},{"month":"Oct","value":18421},{"month":"Nov","value":17899},{"month":"Dec","value":37000}],"logo_color":"#14532d","business_score":99,"lend_score":92,"acquisition_power":87,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":66000,"traffic_trend":"up","listing_views":22000,"listing_favorites":28,"mom_growth":17,"customers":880,"peak_mrr":39220,"asking_price_strike":5700000,"revenue_growth_30d_pct":17,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'ai-text-humanizer',
    'mrtars',
    'AI Text Humanizer',
    null,
    'Transforms AI-generated content into writing that genuinely feels human. Not by swapping words around like every other tool, but through a Human-AI Synergy Engine that actually understands your conten',
    'Artificial Intelligence',
    'live',
    9000,
    'USD',
    9264,
    null,
    16,
    76,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":223},{"month":"Feb","value":267},{"month":"Mar","value":299},{"month":"Apr","value":287},{"month":"May","value":289},{"month":"Jun","value":285},{"month":"Jul","value":294},{"month":"Aug","value":296},{"month":"Sep","value":339},{"month":"Oct","value":389},{"month":"Nov","value":391},{"month":"Dec","value":772}],"logo_color":"#27272a","business_score":80,"lend_score":85,"acquisition_power":80,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":5700,"traffic_trend":"up","listing_views":1900,"listing_favorites":7,"mom_growth":16,"customers":76,"peak_mrr":865,"asking_price_strike":null,"revenue_growth_30d_pct":16,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'confidential-startup',
    'mrtars',
    'Confidential Startup',
    null,
    'SaaS platform that lets users deploy their own AI assistant (powered by OpenClaw) in under 60 seconds. No coding, no server management — users pick a model, connect a messaging app, and they''re live.',
    'Artificial Intelligence',
    'live',
    45000,
    'USD',
    12000,
    null,
    23,
    84,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":292},{"month":"Feb","value":310},{"month":"Mar","value":371},{"month":"Apr","value":440},{"month":"May","value":522},{"month":"Jun","value":604},{"month":"Jul","value":602},{"month":"Aug","value":662},{"month":"Sep","value":774},{"month":"Oct","value":808},{"month":"Nov","value":944},{"month":"Dec","value":1000}],"logo_color":"#4c1d95","business_score":82,"lend_score":86,"acquisition_power":69,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":6300,"traffic_trend":"up","listing_views":2100,"listing_favorites":4,"mom_growth":23,"customers":84,"peak_mrr":1050,"asking_price_strike":null,"revenue_growth_30d_pct":23,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'setter-ai-llc',
    'mrtars',
    'Setter AI LLC',
    null,
    'Setter AI (via TrySetter) is an AI-driven lead engagement and appointment-booking assistant designed to help businesses capture more sales opportunities. It instantly follows up with new leads (in ~10',
    'Artificial Intelligence',
    'live',
    195000,
    'USD',
    82800,
    null,
    21,
    260,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":2089},{"month":"Feb","value":2207},{"month":"Mar","value":2473},{"month":"Apr","value":2902},{"month":"May","value":2961},{"month":"Jun","value":2829},{"month":"Jul","value":3239},{"month":"Aug","value":3530},{"month":"Sep","value":3800},{"month":"Oct","value":4078},{"month":"Nov","value":4002},{"month":"Dec","value":6900}],"logo_color":"#0f172a","business_score":94,"lend_score":91,"acquisition_power":86,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":19500,"traffic_trend":"up","listing_views":6500,"listing_favorites":14,"mom_growth":21,"customers":260,"peak_mrr":7452,"asking_price_strike":230000,"revenue_growth_30d_pct":21,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'aiseoscan',
    'mrtars',
    'AISEOScan',
    null,
    'AI Search Optimization Scanner Scanner built specifically for AI search optimization audit.The platform analyzes websites and generates detailed reports with actionable implementation code for every',
    'Marketing',
    'live',
    2800,
    'USD',
    2124,
    null,
    8750,
    60,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":56},{"month":"Feb","value":58},{"month":"Mar","value":66},{"month":"Apr","value":65},{"month":"May","value":76},{"month":"Jun","value":80},{"month":"Jul","value":81},{"month":"Aug","value":96},{"month":"Sep","value":114},{"month":"Oct","value":124},{"month":"Nov","value":130},{"month":"Dec","value":177}],"logo_color":"#134e4a","business_score":83,"lend_score":74,"acquisition_power":77,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":4500,"traffic_trend":"up","listing_views":1500,"listing_favorites":6,"mom_growth":8750,"customers":60,"peak_mrr":202,"asking_price_strike":3200,"revenue_growth_30d_pct":8750,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'angular-material-blocks',
    'mrtars',
    'Angular Material Blocks',
    null,
    'Rapid Angular UI Development. With Pre-built Blocks, Beautiful Templates & Powerful CLI. Also includes revenues from angular-ui.com (25%), angular-material.dev (14%), themes.angular-material.dev (5%)',
    'Developer Tools',
    'live',
    12000,
    'USD',
    20400,
    null,
    1735,
    24,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":510},{"month":"Feb","value":529},{"month":"Mar","value":600},{"month":"Apr","value":639},{"month":"May","value":708},{"month":"Jun","value":706},{"month":"Jul","value":804},{"month":"Aug","value":880},{"month":"Sep","value":932},{"month":"Oct","value":943},{"month":"Nov","value":954},{"month":"Dec","value":1700}],"logo_color":"#7f1d1d","business_score":97,"lend_score":85,"acquisition_power":92,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":1824,"traffic_trend":"up","listing_views":608,"listing_favorites":0,"mom_growth":1735,"customers":24,"peak_mrr":1836,"asking_price_strike":15000,"revenue_growth_30d_pct":1735,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'sorio-ai-market',
    'mrtars',
    'Sorio AI',
    null,
    'Sorio AI is a platform for creating AI-generated content and viral faceless videos. It lets users create content with different AI models like Veo 3.1, Sora 2, Wan 2.2, and Kling 1.6, while also makin',
    'Content Creation',
    'live',
    25000,
    'USD',
    18000,
    null,
    0,
    20,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":518},{"month":"Feb","value":545},{"month":"Mar","value":647},{"month":"Apr","value":717},{"month":"May","value":766},{"month":"Jun","value":885},{"month":"Jul","value":933},{"month":"Aug","value":1020},{"month":"Sep","value":1222},{"month":"Oct","value":1448},{"month":"Nov","value":1445},{"month":"Dec","value":1500}],"logo_color":"#831843","business_score":75,"lend_score":81,"acquisition_power":76,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":1128,"traffic_trend":"up","listing_views":376,"listing_favorites":3,"mom_growth":0,"customers":20,"peak_mrr":1650,"asking_price_strike":null,"revenue_growth_30d_pct":null,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'prompt-sloth',
    'mrtars',
    'Prompt Sloth',
    null,
    'Your Prompting sucks, we fix it! Turn rough ideas into expert prompts for better AI results. Works across ChatGPT, Claude, and every tool you use.',
    'Artificial Intelligence',
    'live',
    25000,
    'USD',
    15600,
    null,
    505,
    84,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":391},{"month":"Feb","value":396},{"month":"Mar","value":423},{"month":"Apr","value":419},{"month":"May","value":475},{"month":"Jun","value":553},{"month":"Jul","value":653},{"month":"Aug","value":716},{"month":"Sep","value":690},{"month":"Oct","value":769},{"month":"Nov","value":768},{"month":"Dec","value":1300}],"logo_color":"#365314","business_score":95,"lend_score":76,"acquisition_power":85,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":6300,"traffic_trend":"up","listing_views":2100,"listing_favorites":2,"mom_growth":505,"customers":84,"peak_mrr":1391,"asking_price_strike":28000,"revenue_growth_30d_pct":505,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'studyai-fr',
    'mrtars',
    'studyai.fr',
    null,
    'Logiciel saas qui génère des fiches de révision, des quiz et des flashcards par ia pour les étudiants.',
    'SaaS',
    'live',
    15000,
    'USD',
    5352,
    null,
    73,
    20,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":156},{"month":"Feb","value":180},{"month":"Mar","value":206},{"month":"Apr","value":220},{"month":"May","value":243},{"month":"Jun","value":237},{"month":"Jul","value":248},{"month":"Aug","value":258},{"month":"Sep","value":290},{"month":"Oct","value":284},{"month":"Nov","value":319},{"month":"Dec","value":446}],"logo_color":"#1e3a8a","business_score":86,"lend_score":79,"acquisition_power":82,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":500,"traffic_trend":"up","listing_views":1,"listing_favorites":0,"mom_growth":73,"customers":20,"peak_mrr":468,"asking_price_strike":null,"revenue_growth_30d_pct":73,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

insert into public.startups (
    slug, founder_handle, title, tagline, description, industry, stage, asking_price, currency,
    annual_revenue, profit, growth_rate, team_size, founded_year, verified, visibility, status, metadata
  ) values (
    'job-bridge',
    'mrtars',
    'Job Bridge',
    null,
    'JobBridge.io is a real-time AI interview assistant (interview copilot) that gives you instant, contextual answers and suggestions during live job interviews to help you respond confidently and land yo',
    'Artificial Intelligence',
    'live',
    75000,
    'USD',
    36000,
    null,
    26,
    60,
    2022,
    true,
    'public',
    'published',
    '{"monthly_revenue_series":[{"month":"Jan","value":1038},{"month":"Feb","value":1192},{"month":"Mar","value":1380},{"month":"Apr","value":1341},{"month":"May","value":1296},{"month":"Jun","value":1330},{"month":"Jul","value":1558},{"month":"Aug","value":1707},{"month":"Sep","value":2047},{"month":"Oct","value":2054},{"month":"Nov","value":2197},{"month":"Dec","value":3000}],"logo_color":"#0c4a6e","business_score":89,"lend_score":83,"acquisition_power":80,"revenue_verified":true,"revenue_provider":"Stripe","domain_verified":true,"traffic_verified":true,"traffic_monthly_visitors":4500,"traffic_trend":"up","listing_views":1500,"listing_favorites":1,"mom_growth":26,"customers":60,"peak_mrr":3150,"asking_price_strike":null,"revenue_growth_30d_pct":26,"founder_display_name":null}'::jsonb
  ) on conflict (slug) do update set
    title = excluded.title,
    description = excluded.description,
    asking_price = excluded.asking_price,
    annual_revenue = excluded.annual_revenue,
    metadata = excluded.metadata,
    updated_at = now();

commit;