-- Schema v2 full cutover: physical names only (no compat views).
-- Generated by scripts/generate-schema-v2-cutover-migration.mjs

BEGIN;

-- Rewrite stored functions/procedures that still reference legacy relation names.
DO $$
DECLARE
  r record;
  def text;
  newdef text;
BEGIN
  FOR r IN
    SELECT p.oid
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.prokind IN ('f', 'p')
  LOOP
    def := pg_get_functiondef(r.oid);
    newdef := def;
    newdef := replace(newdef, 'public.platform_disposable_email_domains', 'public.trust_disposable_email_domains');
    newdef := replace(newdef, 'public.platform_disposable_email_domains%ROWTYPE', 'public.trust_disposable_email_domains%ROWTYPE');
    newdef := replace(newdef, 'public.business_registration_documents', 'public.trust_registration_documents');
    newdef := replace(newdef, 'public.business_registration_documents%ROWTYPE', 'public.trust_registration_documents%ROWTYPE');
    newdef := replace(newdef, 'public.domain_verification_challenges', 'public.trust_domain_challenges');
    newdef := replace(newdef, 'public.domain_verification_challenges%ROWTYPE', 'public.trust_domain_challenges%ROWTYPE');
    newdef := replace(newdef, 'public.founder_identity_verifications', 'public.trust_founder_identity_checks');
    newdef := replace(newdef, 'public.founder_identity_verifications%ROWTYPE', 'public.trust_founder_identity_checks%ROWTYPE');
    newdef := replace(newdef, 'public.identity_verification_sessions', 'public.trust_identity_sessions');
    newdef := replace(newdef, 'public.identity_verification_sessions%ROWTYPE', 'public.trust_identity_sessions%ROWTYPE');
    newdef := replace(newdef, 'public.business_email_launch_tokens', 'public.sys_business_email_launch_tokens');
    newdef := replace(newdef, 'public.business_email_launch_tokens%ROWTYPE', 'public.sys_business_email_launch_tokens%ROWTYPE');
    newdef := replace(newdef, 'public.business_email_verifications', 'public.trust_business_email_verifications');
    newdef := replace(newdef, 'public.business_email_verifications%ROWTYPE', 'public.trust_business_email_verifications%ROWTYPE');
    newdef := replace(newdef, 'public.person_verification_profiles', 'public.trust_person_profiles');
    newdef := replace(newdef, 'public.person_verification_profiles%ROWTYPE', 'public.trust_person_profiles%ROWTYPE');
    newdef := replace(newdef, 'public.verification_webhook_events', 'public.trust_webhook_events');
    newdef := replace(newdef, 'public.verification_webhook_events%ROWTYPE', 'public.trust_webhook_events%ROWTYPE');
    newdef := replace(newdef, 'public.listing_verification_gates', 'public.trust_listing_gates');
    newdef := replace(newdef, 'public.listing_verification_gates%ROWTYPE', 'public.trust_listing_gates%ROWTYPE');
    newdef := replace(newdef, 'public.sync_worker_launch_tokens', 'public.sys_sync_worker_launch_tokens');
    newdef := replace(newdef, 'public.sync_worker_launch_tokens%ROWTYPE', 'public.sys_sync_worker_launch_tokens%ROWTYPE');
    newdef := replace(newdef, 'public.marketplace_offer_events', 'public.marketplace_offer_notifications');
    newdef := replace(newdef, 'public.marketplace_offer_events%ROWTYPE', 'public.marketplace_offer_notifications%ROWTYPE');
    newdef := replace(newdef, 'public.platform_internal_config', 'public.sys_platform_config');
    newdef := replace(newdef, 'public.platform_internal_config%ROWTYPE', 'public.sys_platform_config%ROWTYPE');
    newdef := replace(newdef, 'public.verified_revenue_metrics', 'public.trust_verified_revenue_metrics');
    newdef := replace(newdef, 'public.verified_revenue_metrics%ROWTYPE', 'public.trust_verified_revenue_metrics%ROWTYPE');
    newdef := replace(newdef, 'public.listing_business_proofs', 'public.marketplace_business_proofs');
    newdef := replace(newdef, 'public.listing_business_proofs%ROWTYPE', 'public.marketplace_business_proofs%ROWTYPE');
    newdef := replace(newdef, 'public.founder_referral_events', 'public.founder_campaign_referral_events');
    newdef := replace(newdef, 'public.founder_referral_events%ROWTYPE', 'public.founder_campaign_referral_events%ROWTYPE');
    newdef := replace(newdef, 'public.integration_connections', 'public.trust_integrations');
    newdef := replace(newdef, 'public.integration_connections%ROWTYPE', 'public.trust_integrations%ROWTYPE');
    newdef := replace(newdef, 'public.integration_credentials', 'public.trust_integration_secrets');
    newdef := replace(newdef, 'public.integration_credentials%ROWTYPE', 'public.trust_integration_secrets%ROWTYPE');
    newdef := replace(newdef, 'public.identity_launch_tokens', 'public.sys_identity_launch_tokens');
    newdef := replace(newdef, 'public.identity_launch_tokens%ROWTYPE', 'public.sys_identity_launch_tokens%ROWTYPE');
    newdef := replace(newdef, 'public.verification_providers', 'public.trust_providers');
    newdef := replace(newdef, 'public.verification_providers%ROWTYPE', 'public.trust_providers%ROWTYPE');
    newdef := replace(newdef, 'public.listing_seller_intake', 'public.marketplace_seller_intake');
    newdef := replace(newdef, 'public.listing_seller_intake%ROWTYPE', 'public.marketplace_seller_intake%ROWTYPE');
    newdef := replace(newdef, 'listing_seller_intake.', 'marketplace_seller_intake.');
    newdef := replace(newdef, 'public.verification_requests', 'public.marketplace_verification_requests');
    newdef := replace(newdef, 'public.verification_requests%ROWTYPE', 'public.marketplace_verification_requests%ROWTYPE');
    newdef := replace(newdef, 'public.integration_sync_jobs', 'public.trust_integration_jobs');
    newdef := replace(newdef, 'public.integration_sync_jobs%ROWTYPE', 'public.trust_integration_jobs%ROWTYPE');
    newdef := replace(newdef, 'public.valuation_adjustments', 'public.trust_valuation_adjustments');
    newdef := replace(newdef, 'public.valuation_adjustments%ROWTYPE', 'public.trust_valuation_adjustments%ROWTYPE');
    newdef := replace(newdef, 'public.listing_fraud_signals', 'public.trust_fraud_signals');
    newdef := replace(newdef, 'public.listing_fraud_signals%ROWTYPE', 'public.trust_fraud_signals%ROWTYPE');
    newdef := replace(newdef, 'public.admin_listing_reviews', 'public.trust_admin_reviews');
    newdef := replace(newdef, 'public.admin_listing_reviews%ROWTYPE', 'public.trust_admin_reviews%ROWTYPE');
    newdef := replace(newdef, 'public.marketplace_profiles', 'public.marketplace_accounts');
    newdef := replace(newdef, 'public.marketplace_profiles%ROWTYPE', 'public.marketplace_accounts%ROWTYPE');
    newdef := replace(newdef, 'public.verification_results', 'public.trust_verification_results');
    newdef := replace(newdef, 'public.verification_results%ROWTYPE', 'public.trust_verification_results%ROWTYPE');
    newdef := replace(newdef, 'public.founder_submissions', 'public.founder_campaign_submissions');
    newdef := replace(newdef, 'public.founder_submissions%ROWTYPE', 'public.founder_campaign_submissions%ROWTYPE');
    newdef := replace(newdef, 'public.verification_events', 'public.trust_verification_events');
    newdef := replace(newdef, 'public.verification_events%ROWTYPE', 'public.trust_verification_events%ROWTYPE');
    newdef := replace(newdef, 'public.trust_score_history', 'public.trust_company_score_history');
    newdef := replace(newdef, 'public.trust_score_history%ROWTYPE', 'public.trust_company_score_history%ROWTYPE');
    newdef := replace(newdef, 'public.accounting_metrics', 'public.trust_accounting_metrics');
    newdef := replace(newdef, 'public.accounting_metrics%ROWTYPE', 'public.trust_accounting_metrics%ROWTYPE');
    newdef := replace(newdef, 'public.startup_interests', 'public.marketplace_buyer_interests');
    newdef := replace(newdef, 'public.startup_interests%ROWTYPE', 'public.marketplace_buyer_interests%ROWTYPE');
    newdef := replace(newdef, 'public.acquisition_deals', 'public.marketplace_acquisitions');
    newdef := replace(newdef, 'public.acquisition_deals%ROWTYPE', 'public.marketplace_acquisitions%ROWTYPE');
    newdef := replace(newdef, 'public.listing_interests', 'public.catalog_listing_interests');
    newdef := replace(newdef, 'public.listing_interests%ROWTYPE', 'public.catalog_listing_interests%ROWTYPE');
    newdef := replace(newdef, 'public.integration_syncs', 'public.trust_integration_sync_runs');
    newdef := replace(newdef, 'public.integration_syncs%ROWTYPE', 'public.trust_integration_sync_runs%ROWTYPE');
    newdef := replace(newdef, 'public.financial_metrics', 'public.trust_financial_metrics');
    newdef := replace(newdef, 'public.financial_metrics%ROWTYPE', 'public.trust_financial_metrics%ROWTYPE');
    newdef := replace(newdef, 'public.valuation_reports', 'public.trust_valuation_reports');
    newdef := replace(newdef, 'public.valuation_reports%ROWTYPE', 'public.trust_valuation_reports%ROWTYPE');
    newdef := replace(newdef, 'public.valuation_history', 'public.trust_valuation_history');
    newdef := replace(newdef, 'public.valuation_history%ROWTYPE', 'public.trust_valuation_history%ROWTYPE');
    newdef := replace(newdef, 'public.valuation_inputs', 'public.trust_valuation_inputs');
    newdef := replace(newdef, 'public.valuation_inputs%ROWTYPE', 'public.trust_valuation_inputs%ROWTYPE');
    newdef := replace(newdef, 'public.startup_metrics', 'public.marketplace_company_metrics');
    newdef := replace(newdef, 'public.startup_metrics%ROWTYPE', 'public.marketplace_company_metrics%ROWTYPE');
    newdef := replace(newdef, 'public.seller_listings', 'public.marketplace_seller_publications');
    newdef := replace(newdef, 'public.seller_listings%ROWTYPE', 'public.marketplace_seller_publications%ROWTYPE');
    newdef := replace(newdef, 'public.traffic_metrics', 'public.trust_traffic_metrics');
    newdef := replace(newdef, 'public.traffic_metrics%ROWTYPE', 'public.trust_traffic_metrics%ROWTYPE');
    newdef := replace(newdef, 'public.ai_insight_runs', 'public.trust_ai_insight_runs');
    newdef := replace(newdef, 'public.ai_insight_runs%ROWTYPE', 'public.trust_ai_insight_runs%ROWTYPE');
    newdef := replace(newdef, 'public.startup_claims', 'public.marketplace_company_claims');
    newdef := replace(newdef, 'public.startup_claims%ROWTYPE', 'public.marketplace_company_claims%ROWTYPE');
    newdef := replace(newdef, 'public.startup_media', 'public.marketplace_company_media');
    newdef := replace(newdef, 'public.startup_media%ROWTYPE', 'public.marketplace_company_media%ROWTYPE');
    newdef := replace(newdef, 'public.conversations', 'public.marketplace_conversations');
    newdef := replace(newdef, 'public.conversations%ROWTYPE', 'public.marketplace_conversations%ROWTYPE');
    newdef := replace(newdef, 'public.trust_signals', 'public.trust_company_signals');
    newdef := replace(newdef, 'public.trust_signals%ROWTYPE', 'public.trust_company_signals%ROWTYPE');
    newdef := replace(newdef, 'public.bid_versions', 'public.marketplace_offer_revisions');
    newdef := replace(newdef, 'public.bid_versions%ROWTYPE', 'public.marketplace_offer_revisions%ROWTYPE');
    newdef := replace(newdef, 'public.bank_metrics', 'public.trust_bank_metrics');
    newdef := replace(newdef, 'public.bank_metrics%ROWTYPE', 'public.trust_bank_metrics%ROWTYPE');
    newdef := replace(newdef, 'public.trust_scores', 'public.trust_company_scores');
    newdef := replace(newdef, 'public.trust_scores%ROWTYPE', 'public.trust_company_scores%ROWTYPE');
    newdef := replace(newdef, 'public.audit_logs', 'public.sys_audit_logs');
    newdef := replace(newdef, 'public.audit_logs%ROWTYPE', 'public.sys_audit_logs%ROWTYPE');
    newdef := replace(newdef, 'public.startups', 'public.marketplace_companies');
    newdef := replace(newdef, 'public.startups%ROWTYPE', 'public.marketplace_companies%ROWTYPE');
    newdef := replace(newdef, 'public.messages', 'public.marketplace_messages');
    newdef := replace(newdef, 'public.messages%ROWTYPE', 'public.marketplace_messages%ROWTYPE');
    newdef := replace(newdef, 'public.listings', 'public.catalog_listings');
    newdef := replace(newdef, 'public.listings%ROWTYPE', 'public.catalog_listings%ROWTYPE');
    newdef := replace(newdef, 'public.bids', 'public.marketplace_offers');
    newdef := replace(newdef, 'public.bids%ROWTYPE', 'public.marketplace_offers%ROWTYPE');
    IF newdef IS DISTINCT FROM def THEN
      BEGIN
        EXECUTE newdef;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE WARNING 'schema_v2_cutover: could not rewrite oid %: %', r.oid, SQLERRM;
      END;
    END IF;
  END LOOP;
END $$;

-- Drop legacy compatibility views (API must use physical names).
DROP VIEW IF EXISTS public.platform_disposable_email_domains CASCADE;
DROP VIEW IF EXISTS public.business_registration_documents CASCADE;
DROP VIEW IF EXISTS public.domain_verification_challenges CASCADE;
DROP VIEW IF EXISTS public.founder_identity_verifications CASCADE;
DROP VIEW IF EXISTS public.identity_verification_sessions CASCADE;
DROP VIEW IF EXISTS public.business_email_launch_tokens CASCADE;
DROP VIEW IF EXISTS public.business_email_verifications CASCADE;
DROP VIEW IF EXISTS public.person_verification_profiles CASCADE;
DROP VIEW IF EXISTS public.verification_webhook_events CASCADE;
DROP VIEW IF EXISTS public.listing_verification_gates CASCADE;
DROP VIEW IF EXISTS public.sync_worker_launch_tokens CASCADE;
DROP VIEW IF EXISTS public.marketplace_offer_events CASCADE;
DROP VIEW IF EXISTS public.platform_internal_config CASCADE;
DROP VIEW IF EXISTS public.verified_revenue_metrics CASCADE;
DROP VIEW IF EXISTS public.listing_business_proofs CASCADE;
DROP VIEW IF EXISTS public.founder_referral_events CASCADE;
DROP VIEW IF EXISTS public.integration_connections CASCADE;
DROP VIEW IF EXISTS public.integration_credentials CASCADE;
DROP VIEW IF EXISTS public.identity_launch_tokens CASCADE;
DROP VIEW IF EXISTS public.verification_providers CASCADE;
DROP VIEW IF EXISTS public.listing_seller_intake CASCADE;
DROP VIEW IF EXISTS public.verification_requests CASCADE;
DROP VIEW IF EXISTS public.integration_sync_jobs CASCADE;
DROP VIEW IF EXISTS public.valuation_adjustments CASCADE;
DROP VIEW IF EXISTS public.listing_fraud_signals CASCADE;
DROP VIEW IF EXISTS public.admin_listing_reviews CASCADE;
DROP VIEW IF EXISTS public.marketplace_profiles CASCADE;
DROP VIEW IF EXISTS public.verification_results CASCADE;
DROP VIEW IF EXISTS public.founder_submissions CASCADE;
DROP VIEW IF EXISTS public.verification_events CASCADE;
DROP VIEW IF EXISTS public.trust_score_history CASCADE;
DROP VIEW IF EXISTS public.accounting_metrics CASCADE;
DROP VIEW IF EXISTS public.startup_interests CASCADE;
DROP VIEW IF EXISTS public.acquisition_deals CASCADE;
DROP VIEW IF EXISTS public.listing_interests CASCADE;
DROP VIEW IF EXISTS public.integration_syncs CASCADE;
DROP VIEW IF EXISTS public.financial_metrics CASCADE;
DROP VIEW IF EXISTS public.valuation_reports CASCADE;
DROP VIEW IF EXISTS public.valuation_history CASCADE;
DROP VIEW IF EXISTS public.valuation_inputs CASCADE;
DROP VIEW IF EXISTS public.startup_metrics CASCADE;
DROP VIEW IF EXISTS public.seller_listings CASCADE;
DROP VIEW IF EXISTS public.traffic_metrics CASCADE;
DROP VIEW IF EXISTS public.ai_insight_runs CASCADE;
DROP VIEW IF EXISTS public.startup_claims CASCADE;
DROP VIEW IF EXISTS public.startup_media CASCADE;
DROP VIEW IF EXISTS public.conversations CASCADE;
DROP VIEW IF EXISTS public.trust_signals CASCADE;
DROP VIEW IF EXISTS public.bid_versions CASCADE;
DROP VIEW IF EXISTS public.bank_metrics CASCADE;
DROP VIEW IF EXISTS public.trust_scores CASCADE;
DROP VIEW IF EXISTS public.audit_logs CASCADE;
DROP VIEW IF EXISTS public.startups CASCADE;
DROP VIEW IF EXISTS public.messages CASCADE;
DROP VIEW IF EXISTS public.listings CASCADE;
DROP VIEW IF EXISTS public.bids CASCADE;

-- Scalability: hot-path indexes (idempotent).
CREATE INDEX IF NOT EXISTS catalog_listings_status_visibility_idx
  ON public.catalog_listings (status, visibility, updated_at DESC);
CREATE INDEX IF NOT EXISTS founder_campaign_submissions_auth_user_idx
  ON public.founder_campaign_submissions (auth_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS trust_verification_results_startup_created_idx
  ON public.trust_verification_results (startup_id, computed_at DESC);
CREATE INDEX IF NOT EXISTS marketplace_seller_publications_startup_idx
  ON public.marketplace_seller_publications (startup_id);

COMMENT ON SCHEMA public IS 'Schema v2 cutover: physical tables only; legacy views removed.';

NOTIFY pgrst, 'reload schema';

COMMIT;
