/**
 * Schema v2 physical PostgREST names (public). Single source of truth for app + workers.
 */
export const SchemaTables = {
  core: {
    users: "users",
    userProfiles: "user_profiles",
    userProducts: "user_products",
    wallets: "wallets",
    walletTransactions: "wallet_transactions",
    referrals: "referrals",
    referralEvents: "referral_events",
    userAppAccess: "user_app_access",
    productSessions: "product_sessions",
    userEvents: "user_events",
    userScores: "user_scores",
    userBadges: "user_badges",
    userOnboardingSessions: "user_onboarding_sessions",
    submissions: "submissions",
  },
  marketplace: {
    companies: "marketplace_companies",
    accounts: "marketplace_accounts",
    companyMedia: "marketplace_company_media",
    companyMetrics: "marketplace_company_metrics",
    buyerInterests: "marketplace_buyer_interests",
    offers: "marketplace_offers",
    offerRevisions: "marketplace_offer_revisions",
    acquisitions: "marketplace_acquisitions",
    offerNotifications: "marketplace_offer_notifications",
    sellerPublications: "marketplace_seller_publications",
    conversations: "marketplace_conversations",
    messages: "marketplace_messages",
    companyClaims: "marketplace_company_claims",
    sellerIntake: "marketplace_seller_intake",
    businessProofs: "marketplace_business_proofs",
    verificationRequests: "marketplace_verification_requests",
  },
  catalog: {
    listings: "catalog_listings",
    listingInterests: "catalog_listing_interests",
  },
  founder: {
    campaignSubmissions: "founder_campaign_submissions",
    campaignReferralEvents: "founder_campaign_referral_events",
  },
  trust: {
    providers: "trust_providers",
    integrations: "trust_integrations",
    integrationSecrets: "trust_integration_secrets",
    integrationSyncRuns: "trust_integration_sync_runs",
    integrationJobs: "trust_integration_jobs",
    verificationResults: "trust_verification_results",
    verificationEvents: "trust_verification_events",
    domainChallenges: "trust_domain_challenges",
    financialMetrics: "trust_financial_metrics",
    trafficMetrics: "trust_traffic_metrics",
    accountingMetrics: "trust_accounting_metrics",
    bankMetrics: "trust_bank_metrics",
    companyScores: "trust_company_scores",
    companyScoreHistory: "trust_company_score_history",
    companySignals: "trust_company_signals",
    valuationReports: "trust_valuation_reports",
    valuationInputs: "trust_valuation_inputs",
    valuationAdjustments: "trust_valuation_adjustments",
    valuationHistory: "trust_valuation_history",
    aiInsightRuns: "trust_ai_insight_runs",
    listingGates: "trust_listing_gates",
    founderIdentityChecks: "trust_founder_identity_checks",
    businessEmailVerifications: "trust_business_email_verifications",
    registrationDocuments: "trust_registration_documents",
    fraudSignals: "trust_fraud_signals",
    adminReviews: "trust_admin_reviews",
    disposableEmailDomains: "trust_disposable_email_domains",
    identitySessions: "trust_identity_sessions",
    webhookEvents: "trust_webhook_events",
    personProfiles: "trust_person_profiles",
    verifiedRevenueMetrics: "trust_verified_revenue_metrics",
    domainDnsDiagnostics: "trust_domain_dns_diagnostics",
    domainRevalidationRuns: "trust_domain_revalidation_runs",
  },
  system: {
    platformConfig: "sys_platform_config",
    auditLogs: "sys_audit_logs",
    identityLaunchTokens: "sys_identity_launch_tokens",
    syncWorkerLaunchTokens: "sys_sync_worker_launch_tokens",
    businessEmailLaunchTokens: "sys_business_email_launch_tokens",
    syncWorkerHealthSnapshots: "sys_sync_worker_health_snapshots",
    mvRefreshRuns: "sys_mv_refresh_runs",
    workerTasks: "sys_worker_tasks",
    webhookEventRegistry: "webhook_event_registry",
    platformAlerts: "platform_alerts",
    platformBackupHealth: "platform_backup_health",
    securityAbuseEvents: "security_abuse_events",
    offerIdempotencyKeys: "offer_idempotency_keys",
    appliedMigrations: "ownerr_applied_migrations",
  },
} as const;

/** Legacy PostgREST name -> physical table (for cutover scripts only). */
export const legacyToPhysicalTable: Record<string, string> = {
  startups: SchemaTables.marketplace.companies,
  marketplace_profiles: SchemaTables.marketplace.accounts,
  startup_media: SchemaTables.marketplace.companyMedia,
  startup_metrics: SchemaTables.marketplace.companyMetrics,
  startup_interests: SchemaTables.marketplace.buyerInterests,
  bids: SchemaTables.marketplace.offers,
  bid_versions: SchemaTables.marketplace.offerRevisions,
  acquisition_deals: SchemaTables.marketplace.acquisitions,
  marketplace_offer_events: SchemaTables.marketplace.offerNotifications,
  seller_listings: SchemaTables.marketplace.sellerPublications,
  conversations: SchemaTables.marketplace.conversations,
  messages: SchemaTables.marketplace.messages,
  startup_claims: SchemaTables.marketplace.companyClaims,
  listing_seller_intake: SchemaTables.marketplace.sellerIntake,
  listing_business_proofs: SchemaTables.marketplace.businessProofs,
  verification_requests: SchemaTables.marketplace.verificationRequests,
  listings: SchemaTables.catalog.listings,
  listing_interests: SchemaTables.catalog.listingInterests,
  founder_submissions: SchemaTables.founder.campaignSubmissions,
  founder_referral_events: SchemaTables.founder.campaignReferralEvents,
  platform_internal_config: SchemaTables.system.platformConfig,
  audit_logs: SchemaTables.system.auditLogs,
  identity_launch_tokens: SchemaTables.system.identityLaunchTokens,
  sync_worker_launch_tokens: SchemaTables.system.syncWorkerLaunchTokens,
  business_email_launch_tokens: SchemaTables.system.businessEmailLaunchTokens,
  verification_providers: SchemaTables.trust.providers,
  integration_connections: SchemaTables.trust.integrations,
  integration_credentials: SchemaTables.trust.integrationSecrets,
  integration_syncs: SchemaTables.trust.integrationSyncRuns,
  integration_sync_jobs: SchemaTables.trust.integrationJobs,
  verification_results: SchemaTables.trust.verificationResults,
  verification_events: SchemaTables.trust.verificationEvents,
  domain_verification_challenges: SchemaTables.trust.domainChallenges,
  financial_metrics: SchemaTables.trust.financialMetrics,
  traffic_metrics: SchemaTables.trust.trafficMetrics,
  accounting_metrics: SchemaTables.trust.accountingMetrics,
  bank_metrics: SchemaTables.trust.bankMetrics,
  trust_scores: SchemaTables.trust.companyScores,
  trust_score_history: SchemaTables.trust.companyScoreHistory,
  trust_signals: SchemaTables.trust.companySignals,
  valuation_reports: SchemaTables.trust.valuationReports,
  valuation_inputs: SchemaTables.trust.valuationInputs,
  valuation_adjustments: SchemaTables.trust.valuationAdjustments,
  valuation_history: SchemaTables.trust.valuationHistory,
  ai_insight_runs: SchemaTables.trust.aiInsightRuns,
  listing_verification_gates: SchemaTables.trust.listingGates,
  founder_identity_verifications: SchemaTables.trust.founderIdentityChecks,
  business_email_verifications: SchemaTables.trust.businessEmailVerifications,
  business_registration_documents: SchemaTables.trust.registrationDocuments,
  listing_fraud_signals: SchemaTables.trust.fraudSignals,
  admin_listing_reviews: SchemaTables.trust.adminReviews,
  platform_disposable_email_domains: SchemaTables.trust.disposableEmailDomains,
  identity_verification_sessions: SchemaTables.trust.identitySessions,
  verification_webhook_events: SchemaTables.trust.webhookEvents,
  person_verification_profiles: SchemaTables.trust.personProfiles,
  verified_revenue_metrics: SchemaTables.trust.verifiedRevenueMetrics,
};
